server:
  port: 8082

#  main:
#    web-application-type: none

wiremock:
  server:
    port: 8081

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, metrics

api-doc:
  enable: false
#  resource: classpath:docs/api/openapi-central.yaml


springdoc:
  swagger-ui:
#    url: classpath:docs/api/openapi-central.yaml
    url: /openapi-central.yaml
